export const APPEND_DIAL_VALUE = 'APPEND_DIAL_VALUE';
export const REMOVE_LAST_CHAR_DIAL_VALUE = 'REMOVE_LAST_CHAR_DIAL_VALUE';
export const REMOVE_DIAL_VALUE = 'REMOVE_DIAL_VALUE';

export const SET_IP = 'SET_IP';
